import { router, useLocalSearchParams } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useMemo, useState } from "react";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { Card, LoadingView, ModulePill, PrimaryButton, QuietButton, SectionLabel, palette } from "@/components/workspace-ui";
import { ScreenContainer } from "@/components/screen-container";
import { AnalysisDraft, ModuleId, STACK_MODULES, TARGET_TYPES, TargetType, validateAnalysisDraft } from "@/lib/workspace-model";
import { useWorkspace } from "@/lib/workspace-context";

export default function NewAnalysisScreen() {
  const { ready, workspaces, createJob } = useWorkspace(); const params = useLocalSearchParams<{ moduleId?: ModuleId }>();
  const initialModules = useMemo(() => STACK_MODULES.some((module) => module.id === params.moduleId) && params.moduleId ? [params.moduleId] : [], [params.moduleId]);
  const [workspaceId, setWorkspaceId] = useState(""); const [targetType, setTargetType] = useState<TargetType>("Mobile package"); const [reference, setReference] = useState(""); const [modules, setModules] = useState<ModuleId[]>(initialModules); const [acknowledged, setAcknowledged] = useState(false);
  if (!ready) return <LoadingView />;
  const activeWorkspaces = workspaces.filter((workspace) => workspace.status === "Active");
  const toggleModule = (id: ModuleId) => setModules((current) => current.includes(id) ? current.filter((module) => module !== id) : [...current, id]);
  const save = () => { const draft: AnalysisDraft = { workspaceId, reference, targetType, modules, acknowledged }; const error = validateAnalysisDraft(draft); if (error) { Alert.alert("Complete this record", error); return; } const job = createJob({ workspaceId, reference, targetType, modules, acknowledgedAt: new Date().toISOString() }); router.replace({ pathname: "/analysis/[id]", params: { id: job.id } }); };
  return <ScreenContainer containerClassName="bg-[#101620]" safeAreaClassName="bg-[#101620]"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.topRow}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><IconSymbol name="chevron.left" size={21} color={palette.text} /></Pressable><Text style={styles.topTitle}>Prepare analysis</Text><View style={styles.backButton} /></View><Text style={styles.eyebrow}>AUTHORIZED USE ONLY</Text><Text style={styles.title}>Create a handoff record</Text><Text style={styles.subtitle}>This saves a local preparation record. It does not initiate remote analysis or transmit a file, database, or credential.</Text>
  <SectionLabel>Workspace</SectionLabel>{activeWorkspaces.length ? <View style={styles.optionList}>{activeWorkspaces.map((workspace) => <Pressable key={workspace.id} accessibilityRole="button" accessibilityState={{ selected: workspaceId === workspace.id }} onPress={() => setWorkspaceId(workspace.id)} style={({ pressed }) => [styles.workspaceOption, workspaceId === workspace.id && styles.workspaceOptionSelected, pressed && styles.pressed]}><View style={styles.optionTextWrap}><Text style={styles.workspaceName}>{workspace.name}</Text><Text style={styles.workspaceMeta}>{workspace.targetType}</Text></View><IconSymbol name={workspaceId === workspace.id ? "checkmark.circle.fill" : "circle"} size={20} color={workspaceId === workspace.id ? palette.teal : palette.muted} /></Pressable>)}</View> : <Card><Text style={styles.cardTitle}>Create an active workspace first</Text><Text style={styles.cardDetail}>An analysis record must belong to an approved local engagement.</Text><View style={styles.cardAction}><PrimaryButton label="Create workspace" onPress={() => router.push("/workspaces")} icon="folder.badge.plus" /></View></Card>}
  <View style={styles.block}><SectionLabel>Target type</SectionLabel><View style={styles.choiceWrap}>{TARGET_TYPES.map((item) => <Pressable key={item} accessibilityRole="button" accessibilityState={{ selected: targetType === item }} onPress={() => setTargetType(item)} style={({ pressed }) => [styles.choice, targetType === item && styles.choiceSelected, pressed && styles.pressed]}><Text style={[styles.choiceText, targetType === item && styles.choiceTextSelected]}>{item}</Text></Pressable>)}</View></View>
  <View style={styles.block}><SectionLabel>Local target reference</SectionLabel><TextInput value={reference} onChangeText={setReference} placeholder="Approved build label or case reference" placeholderTextColor="#718399" returnKeyType="done" style={styles.input} /><Text style={styles.helper}>Keep this reference non-sensitive. Do not store keys, passwords, or private URLs.</Text></View>
  <View style={styles.block}><SectionLabel>Analysis modules</SectionLabel><View style={styles.moduleChoiceList}>{STACK_MODULES.map((module) => { const selected = modules.includes(module.id); return <Pressable key={module.id} accessibilityRole="button" accessibilityState={{ selected }} onPress={() => toggleModule(module.id)} style={({ pressed }) => [styles.moduleChoice, selected && styles.moduleChoiceSelected, pressed && styles.pressed]}><View style={styles.moduleChoiceBody}><ModulePill id={module.id} /><Text style={styles.moduleDescription}>{module.capability}</Text></View><IconSymbol name={selected ? "checkmark.circle.fill" : "plus.circle"} size={20} color={selected ? palette.teal : palette.muted} /></Pressable>; })}</View></View>
  <Card style={styles.authorizationCard}><View style={styles.authorizationIcon}><IconSymbol name="lock.shield" size={17} color={palette.teal} /></View><View style={styles.authorizationText}><Text style={styles.cardTitle}>Authorization acknowledgement</Text><Text style={styles.cardDetail}>I own this target or have documented permission to assess it in the selected scope.</Text></View><Switch value={acknowledged} onValueChange={setAcknowledged} trackColor={{ false: "#3B4B5C", true: "#2B837B" }} thumbColor={acknowledged ? palette.teal : "#D5DEE7"} /></Card>
  <PrimaryButton label="Save analysis record" onPress={save} icon="checkmark.circle.fill" disabled={!activeWorkspaces.length} /><QuietButton label="Cancel" onPress={() => router.back()} icon="xmark.circle" />
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { backgroundColor: palette.base, padding: 20, paddingBottom: 36, gap: 16 }, topRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 5 }, backButton: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, topTitle: { color: palette.text, fontSize: 16, fontWeight: "800" }, eyebrow: { color: palette.teal, fontSize: 11, fontWeight: "800", letterSpacing: 1.2, marginTop: 3 }, title: { color: palette.text, fontSize: 29, lineHeight: 36, fontWeight: "800", letterSpacing: -0.5, marginTop: -11 }, subtitle: { color: palette.muted, fontSize: 14, lineHeight: 20, marginTop: -8 }, block: { gap: 10 }, optionList: { gap: 8 }, workspaceOption: { borderWidth: 1, borderColor: palette.border, borderRadius: 16, backgroundColor: palette.surface, padding: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 }, workspaceOptionSelected: { borderColor: palette.teal, backgroundColor: "#163236" }, optionTextWrap: { flex: 1 }, workspaceName: { color: palette.text, fontSize: 15, fontWeight: "800" }, workspaceMeta: { color: palette.muted, fontSize: 12, marginTop: 3 }, cardTitle: { color: palette.text, fontSize: 15, fontWeight: "800" }, cardDetail: { color: palette.muted, fontSize: 13, lineHeight: 18, marginTop: 4 }, cardAction: { marginTop: 15 }, choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { paddingHorizontal: 11, paddingVertical: 9, borderRadius: 11, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border }, choiceSelected: { backgroundColor: palette.tealMuted, borderColor: palette.teal }, choiceText: { color: palette.muted, fontSize: 13, fontWeight: "700" }, choiceTextSelected: { color: palette.teal }, input: { color: palette.text, fontSize: 15, backgroundColor: palette.surface, borderColor: palette.border, borderWidth: 1, borderRadius: 15, paddingHorizontal: 15, minHeight: 52 }, helper: { color: "#74869A", fontSize: 12, lineHeight: 17, marginTop: -3 }, moduleChoiceList: { gap: 8 }, moduleChoice: { minHeight: 76, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 11, padding: 13, backgroundColor: palette.surface, borderColor: palette.border, borderWidth: 1, borderRadius: 16 }, moduleChoiceSelected: { backgroundColor: "#163236", borderColor: palette.teal }, moduleChoiceBody: { flex: 1, gap: 7 }, moduleDescription: { color: palette.muted, fontSize: 12, lineHeight: 17 }, authorizationCard: { backgroundColor: "#142833", borderColor: "#214A53", flexDirection: "row", alignItems: "center", gap: 11 }, authorizationIcon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: palette.tealMuted }, authorizationText: { flex: 1 }, pressed: { opacity: 0.72 } });
