import { Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { useState } from "react";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { Card, EmptyCard, LoadingView, ModulePill, PrimaryButton, QuietButton, SectionLabel, StatusPill, palette } from "@/components/workspace-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useWorkspace } from "@/lib/workspace-context";
import { formatDate } from "@/lib/workspace-model";
import { trpc } from "@/lib/trpc";

export default function GatewayScreen() {
  const { ready, jobs, updateJob } = useWorkspace();
  const [selectedJobId, setSelectedJobId] = useState<string | null>(null); const [approved, setApproved] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const statusQuery = trpc.gateway.status.useQuery(undefined, { retry: false }); const healthQuery = trpc.gateway.health.useQuery(undefined, { enabled: false, retry: false }); const dispatchMutation = trpc.gateway.dispatch.useMutation();
  if (!ready) return <LoadingView />;
  const selectedJob = jobs.find((job) => job.id === selectedJobId); const dispatchable = jobs.filter((job) => job.state === "Ready");
  const dispatch = async () => { if (!selectedJob || !approved) return; try { const result = await dispatchMutation.mutateAsync({ jobId: selectedJob.id, reference: selectedJob.reference, targetType: selectedJob.targetType, modules: selectedJob.modules, approval: true, approvedAt: new Date().toISOString() }); updateJob(selectedJob.id, { state: "Review", dispatchedAt: new Date().toISOString(), gatewayReceiptId: result.receiptId, gatewayStatus: result.status }); setMessage(`Gateway accepted the record: ${result.status}.`); setSelectedJobId(null); setApproved(false); } catch { setMessage("The gateway did not accept this record. Verify operator access and gateway configuration."); } };
  const configured = statusQuery.data?.configured === true; const health = healthQuery.data;
  return <ScreenContainer containerClassName="bg-[#101620]" safeAreaClassName="bg-[#101620]"><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>OPERATOR CONTROL PLANE</Text><Text style={styles.title}>Private Gateway</Text><Text style={styles.subtitle}>Health checks and dispatches are authenticated through the server. The mobile client never receives the gateway credential.</Text>
  <Card style={styles.statusCard}><View style={styles.statusTop}><View style={styles.statusGlyph}><IconSymbol name="lock.shield" size={19} color={configured ? palette.teal : palette.amber} /></View><View style={styles.statusCopy}><Text style={styles.statusTitle}>{configured ? "Operator gateway configured" : "Operator gateway not configured"}</Text><Text style={styles.statusDetail}>{configured ? `Endpoint: ${statusQuery.data?.endpoint}` : "The project owner must provide an HTTPS endpoint and service token before monitoring or dispatch is available."}</Text></View></View>{statusQuery.error ? <Text style={styles.warning}>Operator sign-in is required to view gateway state.</Text> : null}{configured ? <View style={styles.statusAction}><PrimaryButton label={healthQuery.isFetching ? "Checking gateway…" : "Check stack health"} onPress={() => void healthQuery.refetch()} icon="server.rack" disabled={healthQuery.isFetching} /></View> : null}{health ? <View style={styles.healthRow}><View style={[styles.healthDot, { backgroundColor: health.reachable ? "#74D6A1" : palette.rose }]} /><Text style={styles.healthText}>{health.status}</Text></View> : null}</Card>
  {message ? <Card style={styles.messageCard}><Text style={styles.messageText}>{message}</Text><QuietButton label="Dismiss" onPress={() => setMessage(null)} icon="xmark.circle" /></Card> : null}
  <SectionLabel>Approved dispatch queue</SectionLabel>{dispatchable.length ? dispatchable.map((job) => <Card key={job.id} style={styles.jobCard}><View style={styles.jobHeading}><Text style={styles.jobRef} numberOfLines={1}>{job.reference}</Text><StatusPill state={job.state} /></View><View style={styles.modules}>{job.modules.map((moduleId) => <ModulePill key={moduleId} id={moduleId} />)}</View><Text style={styles.jobMeta}>Prepared {formatDate(job.createdAt)} · Explicit operator approval required</Text><View style={styles.jobAction}><PrimaryButton label="Review dispatch" onPress={() => { setApproved(false); setSelectedJobId(job.id); }} icon="lock.shield" disabled={!configured || Boolean(statusQuery.error)} /></View></Card>) : <EmptyCard title="No records ready for dispatch" detail="Prepare an authorized analysis record. It will appear here only when it is ready for an operator review." />}
  {jobs.filter((job) => job.gatewayReceiptId).length ? <View style={styles.history}><SectionLabel>Dispatch history</SectionLabel>{jobs.filter((job) => job.gatewayReceiptId).map((job) => <Card key={job.id} style={styles.historyCard}><Text style={styles.historyTitle}>{job.reference}</Text><Text style={styles.historyMeta}>{job.gatewayStatus ?? "Accepted"} · {job.dispatchedAt ? formatDate(job.dispatchedAt) : "Recorded"}</Text></Card>)}</View> : null}
  </ScrollView><Modal transparent visible={Boolean(selectedJob)} animationType="slide" onRequestClose={() => setSelectedJobId(null)}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.sheetHandle} /><Text style={styles.sheetTitle}>Approve gateway dispatch</Text><Text style={styles.sheetDetail}>This sends only the selected record’s reference, target type, approved modules, and approval time to the configured gateway. It cannot send credentials, file contents, or arbitrary commands.</Text><Card style={styles.approvalCard}><View style={styles.approvalRow}><View style={styles.approvalText}><Text style={styles.approvalTitle}>I have authority to dispatch this job</Text><Text style={styles.approvalDetail}>The gateway enforces its own module and target policy.</Text></View><Switch value={approved} onValueChange={setApproved} trackColor={{ false: "#3B4B5C", true: "#2B837B" }} thumbColor={approved ? palette.teal : "#D5DEE7"} /></View></Card><PrimaryButton label={dispatchMutation.isPending ? "Dispatching…" : "Confirm dispatch"} onPress={() => void dispatch()} icon="checkmark.circle.fill" disabled={!approved || dispatchMutation.isPending} /><QuietButton label="Cancel" onPress={() => { setSelectedJobId(null); setApproved(false); }} icon="xmark.circle" /></View></View></Modal></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34, backgroundColor: palette.base, gap: 16 }, eyebrow: { color: palette.teal, fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { color: palette.text, fontSize: 31, lineHeight: 38, fontWeight: "800", letterSpacing: -0.6, marginTop: -11 }, subtitle: { color: palette.muted, fontSize: 14, lineHeight: 20, marginTop: -7 }, statusCard: { backgroundColor: "#142833", borderColor: "#214A53" }, statusTop: { flexDirection: "row", gap: 12 }, statusGlyph: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: palette.tealMuted }, statusCopy: { flex: 1 }, statusTitle: { color: palette.text, fontSize: 15, fontWeight: "800" }, statusDetail: { color: palette.muted, fontSize: 13, lineHeight: 18, marginTop: 3 }, statusAction: { marginTop: 15 }, healthRow: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 13 }, healthDot: { width: 8, height: 8, borderRadius: 4 }, healthText: { color: palette.text, fontSize: 13, fontWeight: "800" }, warning: { color: palette.amber, fontSize: 12, lineHeight: 17, marginTop: 12 }, messageCard: { backgroundColor: "#1A2F39", borderColor: "#276572" }, messageText: { color: palette.text, fontSize: 14, lineHeight: 20 }, jobCard: { gap: 11 }, jobHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, jobRef: { color: palette.text, fontSize: 16, fontWeight: "800", flex: 1 }, modules: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, jobMeta: { color: palette.muted, fontSize: 12, lineHeight: 17 }, jobAction: { marginTop: 2 }, history: { gap: 0, marginTop: 4 }, historyCard: { paddingVertical: 14, marginBottom: 8 }, historyTitle: { color: palette.text, fontSize: 14, fontWeight: "800" }, historyMeta: { color: palette.muted, fontSize: 12, marginTop: 4 }, backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(2, 7, 12, 0.74)" }, sheet: { backgroundColor: palette.surfaceStrong, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, paddingBottom: 34, gap: 16 }, sheetHandle: { height: 4, width: 42, borderRadius: 2, backgroundColor: "#607083", alignSelf: "center", marginTop: -8 }, sheetTitle: { color: palette.text, fontSize: 21, fontWeight: "800" }, sheetDetail: { color: palette.muted, fontSize: 14, lineHeight: 20 }, approvalCard: { backgroundColor: palette.base }, approvalRow: { flexDirection: "row", alignItems: "center", gap: 12 }, approvalText: { flex: 1 }, approvalTitle: { color: palette.text, fontSize: 14, fontWeight: "800" }, approvalDetail: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 3 } });
