import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useMemo, useState } from "react";
import { EmptyCard, LoadingView, PrimaryButton, SectionLabel, palette } from "@/components/workspace-ui";
import { ScreenContainer } from "@/components/screen-container";
import { FindingSeverity, FINDING_SEVERITIES, formatDate, moduleById } from "@/lib/workspace-model";
import { useWorkspace } from "@/lib/workspace-context";
const severityColors: Record<FindingSeverity, string> = { Critical: "#F18A93", High: "#F3B34C", Medium: "#F7D87B", Low: "#83D2C7", Info: "#AAB7C5" };
export default function InsightsScreen() {
  const { ready, findings, jobs } = useWorkspace(); const [filter, setFilter] = useState<FindingSeverity | "All">("All"); const visible = useMemo(() => findings.filter((finding) => filter === "All" || finding.severity === filter), [filter, findings]); if (!ready) return <LoadingView />;
  return <ScreenContainer containerClassName="bg-[#101620]" safeAreaClassName="bg-[#101620]"><FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={styles.content}
    ListHeaderComponent={<><Text style={styles.eyebrow}>LOCAL REVIEW NOTES</Text><Text style={styles.title}>Insights</Text><Text style={styles.subtitle}>Save confirmed observations from your authorized environment. This screen starts empty by design.</Text><View style={styles.filterRow}>{["All", ...FINDING_SEVERITIES].map((item) => <Pressable key={item} accessibilityRole="button" accessibilityState={{ selected: filter === item }} onPress={() => setFilter(item as FindingSeverity | "All")} style={({ pressed }) => [styles.filter, filter === item && styles.filterSelected, pressed && styles.pressed]}><Text style={[styles.filterText, filter === item && styles.filterTextSelected]}>{item}</Text></Pressable>)}</View>{visible.length > 0 ? <SectionLabel>{`${visible.length} saved insight${visible.length === 1 ? "" : "s"}`}</SectionLabel> : null}</>}
    renderItem={({ item }) => { const module = moduleById(item.source); const job = jobs.find((candidate) => candidate.id === item.jobId); return <Pressable accessibilityRole="button" accessibilityLabel={`Open analysis for ${item.title}`} onPress={() => router.push({ pathname: "/analysis/[id]", params: { id: item.jobId } })} style={({ pressed }) => [styles.finding, pressed && styles.pressed]}><View style={styles.findingTop}><Text style={[styles.severity, { color: severityColors[item.severity] }]}>{item.severity}</Text><Text style={styles.source}>{module.shortName}</Text></View><Text style={styles.findingTitle}>{item.title}</Text>{item.detail ? <Text style={styles.findingDetail} numberOfLines={2}>{item.detail}</Text> : null}<Text style={styles.findingMeta}>{job?.reference ?? "Analysis record"} · {formatDate(item.createdAt)}</Text></Pressable>; }} ItemSeparatorComponent={() => <View style={{ height: 10 }} />}
    ListEmptyComponent={<EmptyCard title={filter === "All" ? "No saved insights" : `No ${filter.toLowerCase()} insights`} detail={jobs.length ? "When you have an approved analysis record, add only observations you have verified." : "Prepare an authorized analysis record first, then capture confirmed observations from it."} action={<PrimaryButton label={jobs.length ? "Record insight" : "Prepare analysis"} onPress={() => router.push(jobs.length ? "/finding/new" : "/analysis/new")} icon={jobs.length ? "square.and.pencil" : "plus"} />} />}
  /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 30, backgroundColor: palette.base, flexGrow: 1 }, eyebrow: { color: palette.teal, fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { color: palette.text, fontSize: 31, lineHeight: 38, fontWeight: "800", letterSpacing: -0.6, marginTop: 3 }, subtitle: { color: palette.muted, fontSize: 14, lineHeight: 20, marginTop: 8, marginBottom: 17 }, filterRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 22 }, filter: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, filterSelected: { borderColor: palette.teal, backgroundColor: palette.tealMuted }, filterText: { color: palette.muted, fontSize: 12, fontWeight: "800" }, filterTextSelected: { color: palette.teal }, pressed: { opacity: 0.72 }, finding: { padding: 16, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border, borderRadius: 18 }, findingTop: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 }, severity: { fontSize: 12, fontWeight: "900", letterSpacing: 0.7, textTransform: "uppercase" }, source: { color: palette.muted, fontSize: 12, fontWeight: "700" }, findingTitle: { color: palette.text, fontSize: 16, lineHeight: 21, fontWeight: "800" }, findingDetail: { color: palette.muted, fontSize: 13, lineHeight: 18, marginTop: 6 }, findingMeta: { color: "#74869A", fontSize: 12, marginTop: 11 } });
