import { router, useLocalSearchParams } from "expo-router";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { Card, EmptyCard, LoadingView, ModulePill, PrimaryButton, SectionLabel, StatusPill, palette } from "@/components/workspace-ui";
import { ScreenContainer } from "@/components/screen-container";
import { formatDate } from "@/lib/workspace-model";
import { useWorkspace } from "@/lib/workspace-context";
export default function WorkspaceDetailScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const { ready, workspaces, jobs, archiveWorkspace } = useWorkspace(); const workspace = workspaces.find((candidate) => candidate.id === id); const workspaceJobs = jobs.filter((job) => job.workspaceId === id); if (!ready) return <LoadingView />; if (!workspace) return <MissingWorkspace />; const archive = () => Alert.alert("Archive workspace?", "Local records remain visible, but new analysis records will not be attached here.", [{ text: "Cancel", style: "cancel" }, { text: "Archive", style: "destructive", onPress: () => archiveWorkspace(workspace.id) }]); return <ScreenContainer containerClassName="bg-[#101620]" safeAreaClassName="bg-[#101620]"><FlatList data={workspaceJobs} keyExtractor={(item) => item.id} contentContainerStyle={styles.content}
  ListHeaderComponent={<><View style={styles.topRow}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><IconSymbol name="chevron.left" size={21} color={palette.text} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Archive workspace" onPress={archive} style={({ pressed }) => [styles.archiveButton, pressed && styles.pressed]}><IconSymbol name="archivebox" size={18} color={palette.muted} /></Pressable></View><Text style={styles.eyebrow}>{workspace.status === "Active" ? "ACTIVE WORKSPACE" : "ARCHIVED WORKSPACE"}</Text><Text style={styles.title}>{workspace.name}</Text><Text style={styles.subtitle}>{workspace.targetType} · Created {formatDate(workspace.createdAt)}</Text><View style={styles.actionArea}>{workspace.status === "Active" ? <PrimaryButton label="Prepare analysis" onPress={() => router.push("/analysis/new")} icon="plus" /> : <Card><Text style={styles.cardTitle}>This workspace is archived</Text><Text style={styles.cardDetail}>Existing records are retained locally. Create or reopen an active workspace for new work.</Text></Card>}</View><SectionLabel>{workspaceJobs.length ? `${workspaceJobs.length} analysis record${workspaceJobs.length === 1 ? "" : "s"}` : "Analysis timeline"}</SectionLabel></>}
  renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Open analysis ${item.reference}`} onPress={() => router.push({ pathname: "/analysis/[id]", params: { id: item.id } })} style={({ pressed }) => [styles.jobRow, pressed && styles.pressed]}><View style={styles.jobBody}><View style={styles.jobTop}><Text style={styles.jobRef} numberOfLines={1}>{item.reference}</Text><StatusPill state={item.state} /></View><View style={styles.moduleRow}>{item.modules.map((moduleId) => <ModulePill key={moduleId} id={moduleId} />)}</View><Text style={styles.jobDate}>Prepared {formatDate(item.createdAt)}</Text></View><IconSymbol name="chevron.right" size={18} color={palette.muted} /></Pressable>} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListEmptyComponent={<EmptyCard title="No analysis records" detail="Prepare a local handoff record when you are ready to coordinate an authorized review." action={workspace.status === "Active" ? <PrimaryButton label="Prepare analysis" onPress={() => router.push("/analysis/new")} icon="plus" /> : undefined} />}
  /></ScreenContainer>; }
function MissingWorkspace() { return <ScreenContainer containerClassName="bg-[#101620]" safeAreaClassName="bg-[#101620]"><View style={styles.missing}><Text style={styles.title}>Workspace unavailable</Text><Text style={styles.subtitle}>It may have been cleared from this device.</Text><PrimaryButton label="View workspaces" onPress={() => router.replace("/workspaces")} icon="folder.fill" /></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34, backgroundColor: palette.base, flexGrow: 1 }, topRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 17 }, backButton: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, archiveButton: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, eyebrow: { color: palette.teal, fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { color: palette.text, fontSize: 28, lineHeight: 35, fontWeight: "800", letterSpacing: -0.5, marginTop: 3 }, subtitle: { color: palette.muted, fontSize: 14, lineHeight: 20, marginTop: 5 }, actionArea: { marginTop: 19, marginBottom: 22 }, jobRow: { flexDirection: "row", alignItems: "center", gap: 12, padding: 15, borderRadius: 18, borderColor: palette.border, borderWidth: 1, backgroundColor: palette.surface }, jobBody: { flex: 1, gap: 8 }, jobTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 }, jobRef: { color: palette.text, fontSize: 15, fontWeight: "800", flex: 1 }, moduleRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, jobDate: { color: palette.muted, fontSize: 12 }, cardTitle: { color: palette.text, fontSize: 15, fontWeight: "800" }, cardDetail: { color: palette.muted, fontSize: 13, lineHeight: 18, marginTop: 4 }, pressed: { opacity: 0.72 }, missing: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28, gap: 12 } });
